### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by billburnseh**
Reflected the change from google chat to slack.

### CODE REVIEW

**Comment by billburnseh** [comment]
Reflected the change from google chat to slack.

**Review by billburnseh — COMMENTED** [review]
Update of chat room, looks good.

**Review by billburnseh — COMMENTED** [review]
All set

**Review by tumido — COMMENTED** [review]
Merging before transfer to https://github.com/operate-first/support
/lgtm
/approve

**Pull request merged**
